routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = App\Product::paginate(4);
    return view('welcome', compact('products'));
});

Auth::routes();
// Route::get('/home','HomeController')
//, 'middleware' => ['admin','auth']
Route::group(['prefix' => 'admin'], function(){
Route::resource('/','AdminController');
Route::resource('/home','AdminController');
Route::resource('/product','ProductesController');
Route::resource('/category','CateroriesController');

});

Route::get('/products','ProductesController@allproducts')->name('allproducts');























//***************************************************************//
//-------------------USER---------------------------------------//
Route::resource('/user','UserController');
Route::get('/user','UserController@index');
Route::post('/user/create','UserController@store');
Route::any('/user/destroy/{id}','TaskController@destroy');
Route::get('/user/{id}/edit','TaskController@edit');
Route::Post('/user/update','TaskController@update');
//Route::get('','')

//***********************************************************//
//--------------------TASK-----------------------------------//
Route::get('/task','TaskController@index');
//Route::resource('/task','TaskController');
Route::any('/task/destroy/{id}','TaskController@destroy');
Route::Post('/task/gadda','TaskController@update');
Route::get('/task/{id}/edit','TaskController@edit');
Route::get('/task/search','TaskController@');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function product()
    {
        return $this->hasMany(Product::class, "product_id");
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.includes.main_admin')
@section('title','New Category')
@section('content')

<div class="container">
    <div class="row">
        @include('admin.includes.sidebar_admin')
         <div class="col-md-9">
              <div class="panel panel-primary">
      <div class="panel-heading">Create New Category</div>
      <div class="panel-body">

        <form action="{{route('category.store')}}" method="POST">
          {{csrf_field()}}
          <div class="form-group">
            <label fae="Titel">Name: </lable>
            <input type="text" name="Name" class="form-control" placeholder="Name Category..">
          </div>

          

          <button type="submit" class="btn btn-success">Submit</button>
          
        </form>
        
      </div>
    </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.includes.main_admin')
@section('title','Edit Category')
@section('content')

<div class="container">
    <div class="row">
        @include('admin.includes.sidebar_admin')
         <div class="col-md-9">
              <div class="panel panel-primary">
      <div class="panel-heading">Edit Category</div>
      <div class="panel-body">

        <form action="{{route('category.update', $category->id)}}" enctype="multipart/form-data"  method="POST">
          {{csrf_field()}}
          {{method_field('put')}}
          <div class="form-group">
            <label fae="Titel">Name: </lable>
            <input type="text" name="Name" class="form-control" value="{{$category->name}}">
          </div>

          

          <button type="submit" class="btn btn-success">Submit</button>
          
        </form>
        
      </div>
    </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/category/index.blade.php
@extends('admin.includes.main_admin')
@section('title','categories')
@section('content')

<div class="container">
    <div class="row">
        @include('admin.includes.sidebar_admin')
         <div class="col-md-9">
              <div class="panel panel-primary">
      <div class="panel-heading">All categories</div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>NO.</th>
              <th>Name</th>
            </tr>
          </thead>
            <tbody>
            @foreach($category as $categories)
            <tr>
                <td>{{$categories->id}}</td>
                <td>{{$categories->name}}</td>
                <td width="10">
                 <a href="{{route('category.edit', $categories->id)}}" class="btn btn-success btn-sm">Edit</a>
                </td>
                <td>
                 <form action="{{route('category.destroy', $categories->id)}}" method="POST">
                 {{csrf_field()}}
                 {{method_field('DELETE')}}
                 <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                 </form>
                </td>
              </tr>
              @endforeach
            </tbody>
        </table>
        </div>
    </div>
    <div class="text-center">
        {!! $category->links(); !!}
        </div>
    </div>
  </div>
</div>

@endsection