routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = App\Product::paginate(4);
    return view('welcome', compact('products'));
});

Auth::routes();
// Route::get('/home','HomeController')
//, 'middleware' => ['admin','auth']
Route::group(['prefix' => 'admin'], function(){
Route::resource('/','AdminController');
Route::resource('/home','AdminController');
Route::resource('/product','ProductesController');
Route::resource('/category','CateroriesController');

});

Route::get('/products','ProductesController@allproducts')->name('allproducts');























//***************************************************************//
//-------------------USER---------------------------------------//
Route::resource('/user','UserController');
Route::get('/user','UserController@index');
Route::post('/user/create','UserController@store');
Route::any('/user/destroy/{id}','TaskController@destroy');
Route::get('/user/{id}/edit','TaskController@edit');
Route::Post('/user/update','TaskController@update');
//Route::get('','')

//***********************************************************//
//--------------------TASK-----------------------------------//
Route::get('/task','TaskController@index');
//Route::resource('/task','TaskController');
Route::any('/task/destroy/{id}','TaskController@destroy');
Route::Post('/task/gadda','TaskController@update');
Route::get('/task/{id}/edit','TaskController@edit');
Route::get('/task/search','TaskController@');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.includes.main_admin')
@section('title','New Product')
@section('content')

<div class="container">
    <div class="row">
        @include('admin.includes.sidebar_admin')
         <div class="col-md-9">
              <div class="panel panel-primary">
      <div class="panel-heading">All Products</div>
      <div class="panel-body">

        <form action="{{route('product.store')}}" enctype="multipart/form-data"  method="POST">
          {{csrf_field()}}
          <div class="form-group">
            <label for="Titel">Title: </lable>
            <input type="text" name="Title" class="form-control" placeholder="Title..">
          </div>

          <div class="form-group">
            <label for="Description">Description: </lable>
            <input type="text" name="Description" class="form-control" placeholder="Description..">
          </div>

          <div class="form-group">
            <label for="Price">Price: </lable>
            <input type="text" name="Price" class="form-control" placeholder="Price..">
          </div>

          <div class="form-group">
            <label for="category_id">Category: </lable>
            <select name="category_id" class="form-control">
              <option value="" disabled selected>Select Category</option>
              @foreach($categories as $category)
              <option value="{{$category->id}}">{{$category->name}}</option>
              @endforeach
            </select>
          </div>

          <div class="form-group">
            <label for="Image">Image: </lable>
            <input type="file" name="Image" class="form-control">
          </div>

          <button type="submit" class="btn btn-success">Submit</button>
          
        </form>
        
      </div>
    </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.includes.main_admin')
@section('title','Edit Product')
@section('content')

<div class="container">
    <div class="row">
        @include('admin.includes.sidebar_admin')
         <div class="col-md-9">
              <div class="panel panel-primary">
      <div class="panel-heading">Edit Products</div>
      <div class="panel-body">

        <form action="{{route('product.update', $product->id)}}" enctype="multipart/form-data"  method="POST">
          {{csrf_field()}}
          {{method_field('put')}}
          <div class="form-group">
            <label fae="Titel">Title: </lable>
            <input type="text" name="Title" class="form-control" value="{{$product->title}}">
          </div>

          <div class="form-group">
            <label fae="Description">Description: </lable>
            <input type="text" name="Description" class="form-control" value="{{$product->description}}">
          </div>

          <div class="form-group">
            <label fae="Price">Price: </lable>
            <input type="text" name="Price" class="form-control"  value="{{$product->price}}">
          </div>

          <div class="form-group">
            <label for="category_id">Category: </lable>
            <select name="category_id" class="form-control">
              <option value="" disabled selected>Select Category</option>
              @foreach($categories as $category)
              <option value="{{$category->id}}" <?php if($product->Category_Id == $category->id){echo "selected";}?> >{{$category->name}}</option>
              @endforeach
            </select>
          </div>


          <div class="form-group">
            <label fae="Image">Image: </lable>
            <input type="file" name="Image" class="form-control">
          </div>

          <div class="form-group">
            <img style="width: 50%" src="{{asset('images/'.$product->image)}}" >
          </div>

          <button type="submit" class="btn btn-success">Submit</button>
          
        </form>
        
      </div>
    </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/product/index.blade.php
@extends('admin.includes.main_admin')
@section('title','Products')
@section('content')

<div class="container">
    <div class="row">
        @include('admin.includes.sidebar_admin')
         <div class="col-md-9">
              <div class="panel panel-primary">
      <div class="panel-heading">All Products</div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Image</th>
              <th>Title</th>
              <th>Description</th>
              <th>Price</th>
            </tr>
          </thead>
            <tbody>
              @foreach($product as $products)
              <tr>
                <td width="150"><img style="width:100%"  src="{{asset('images/'.$products->image)}}"/></td>
                <td>{{$products->title}}</td>
                <td>{{$products->description}}</td>
                <td>{{$products->price}}</td>
                
                <td>
                 <a href="{{route('product.edit', $products->id)}}" class="btn btn-success btn-sm">Edit</a>
                </td>
                <td>
                 <form action="{{route('product.destroy', $products->id)}}" method="POST">
                 {{csrf_field()}}
                 {{method_field('DELETE')}}
                 <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                 </form>
                </td>
              </tr>
              @endforeach
            </tbody>
        </table>
        </div>
    </div>
    <div class="text-center">
        {!! $product->links(); !!}
        </div>
    </div>
  </div>
</div>

@endsection