routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = App\Product::paginate(4);
    return view('welcome', compact('products'));
});

Auth::routes();
// Route::get('/home','HomeController')
//, 'middleware' => ['admin','auth']
Route::group(['prefix' => 'admin'], function(){
Route::resource('/','AdminController');
Route::resource('/home','AdminController');
Route::resource('/product','ProductesController');
Route::resource('/category','CateroriesController');

});

Route::get('/products','ProductesController@allproducts')->name('allproducts');























//***************************************************************//
//-------------------USER---------------------------------------//
Route::resource('/user','UserController');
Route::get('/user','UserController@index');
Route::post('/user/create','UserController@store');
Route::any('/user/destroy/{id}','TaskController@destroy');
Route::get('/user/{id}/edit','TaskController@edit');
Route::Post('/user/update','TaskController@update');
//Route::get('','')

//***********************************************************//
//--------------------TASK-----------------------------------//
Route::get('/task','TaskController@index');
//Route::resource('/task','TaskController');
Route::any('/task/destroy/{id}','TaskController@destroy');
Route::Post('/task/gadda','TaskController@update');
Route::get('/task/{id}/edit','TaskController@edit');
Route::get('/task/search','TaskController@');

resources/views/admin/includes/info.blade.php
@if(session('info'))
<div class="alert alert-success">
  {{session('info')}}
</div>
@endif

<!-- @if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif -->


@if(session('alert'))
<div class="alert alert-danger">
  {{session('alert')}}
</div>
@endif

resources/views/admin/includes/main_admin.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>
     
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/admin') }}">
                       ADMIN DASHBOARD
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                      
                    </ul> 
                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar">
                    @include('layouts.menu')
                    </ul>
                    </div>
 
                
            </div>
        </nav>
        
        <br>
        <div class="container">
        @include('admin.includes.info')
        </div>
    
           @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 
    @yield('js')
</body>
</html>

resources/views/admin/includes/sidebar_admin.blade.php
<div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">Menu</div>
        <div class="list-group"> 
	       <a data-toggle="collapse" href="#orders" class="list-group-item">Orders</a>
          <div id="orders" class="panel-collapse collapse">
        	<div class="panel-footer"> </div>
          <div class="panel-body">
              <a href="#" class="list-group-item">All Orders</a>
              <a href="#" class="list-group-item">Pending Orders</a>
              <a href="#" class="list-group-item">Delivered</a>
          </div>
          </div>
              <a data-toggle="collapse" href="#product" class="list-group-item">Product</a>
          <div id="product" class="panel-collapse collapse">
          <div class="panel-body">
              <a href="{{route('product.index')}}" class="list-group-item">All Product</a>
              <a href="{{route('product.create')}}" class="list-group-item">Create Product</a>
        </div>
    <div class="panel-footer"> </div>
</div>
 



 

<a data-toggle="collapse" href="#category" class="list-group-item">Category</a>

    <div id="category" class="panel-collapse collapse">
    	<div class="panel-footer"> </div>
      <div class="panel-body">
      	  <a href="{{route('category.index')}}" class="list-group-item">All Category</a> 

          <a href="{{route('category.create')}}" class="list-group-item">Add Category</a> 
      </div>
 
    </div>
 

</div>
 
    </div>

      
 
        </div>